version: "3.8"

services:
  app:
    build: .
    image: my-rust-api:latest
    ports:
      - "8080:8080"
    volumes:
      - ./movies.db:/app/movies.db
    environment:
      - DATABASE_URL=sqlite:/app/movies.db
    restart: always
